title: Nelcifran Magalhães
description: Software Developer
baseurl: ""
url: "https://NelcifranMagalhaes.github.io"

# site settings
taglong: Software Developer
tagshort: Blog

# author settings
author:
  name: Nelcifran Magalhães
  email: nelcifranpires@gmail.com
photo: assets/files/me.jpg

# profile links
profile:
  github: https://github.com/NelcifranMagalhaes
  linkedin: https://www.linkedin.com/in/nelcifranpires/
  cv: true
  

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - .github/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-sitemap
