# Site settings
title: Nelcifran MagalhÃ£es
email: # Add your email here (optional)
description: >-
  My portfolio website showcasing my projects and skills.
baseurl: ""
url: "https://NelcifranMagalhaes.github.io"

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
